[workspace]
resolver = "2"
members = ["crates/server_core"]

[workspace.package]
repository = "https://github.com/oneofthezombies/graphql-ice"
license = "MIT OR Apache-2.0"
edition = "2021"
authors = ["oneofthezombies <hunhoekim@gmail.com>"]
