# :schema /graphql-ice/node_modules/wrangler/config-schema.json
name = "cloudflare-workers"
main = "src/wasm-query-module.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
